.PHONY: schema version v1
schema:
	curl -X GET http://localhost:8081/subjects
version:
	curl -X GET http://localhost:8081/subjects/user-info-value/versions
v1:
	curl -X GET http://localhost:8081/subjects/user-info-value/versions/1
